version: '3'

services:
    nginx:
      build: ./requirements/nginx
      image: img_nginx
      container_name: nginx
      restart: unless-stopped
      ports:
        - "443:443"

    mariadb:
      build: ./requirements/mariadb
      image: img_mariadb
      container_name: mariadb
      restart: unless-stopped
      ports:
        - "3306:3306/tcp"
      volumes:
        - mdb_data:/var/lib/mysql
    
    wordpress:
      build: ./requirements/wordpress
      image: img_wordpress
      container_name: wordpress
      restart: unless-stopped
      ports:
        - "9000:9000/tcp"

volumes:
    wp_data:
        # using external volume created in custom directory
        external: true
    mdb_data:
        external: true